// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jztvpmnciwoefbrewnms.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6dHZwbW5jaXdvZWZicmV3bm1zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzAzMTcsImV4cCI6MjA3MTIwNjMxN30.xHOUVvIXdjml3NKXgLmqc2Sl9CHUBH1_EDG1KibdW1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});