// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlbsxswffeogikqboskb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsYnN4c3dmZmVvZ2lrcWJvc2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MTg0NjQsImV4cCI6MjA3MTI5NDQ2NH0.5Afaln-RlaKzgBuzUerSARK1BjkRlcovIDde0sy0i4I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});